1stmodel
mrpetrakova2000/coming_soon_ai_product_hack pull request #4
Opened 2024-09-08 11:23 UTC by katyachemistry

2024-09-08 19:00 UTC, Evgenii-Iurin requested changes
Looks good! I would like to ask you to rewrite it using the standard machine learning library, PyTorch. Please note that in the Dataset class, features should never be generated or created. Instead, the Dataset class should only handle data indexing and retrieval through the __getitem__ and __len__ methods, while feature extraction or any data processing should be managed in a separate function or module

2024-09-09 12:26 UTC, katyachemistry commented on backend/ML/LGBM_1_day.py
> +def smape(preds, target):
in sklearn there is only mape :(

2024-09-09 12:33 UTC, katyachemistry commented on backend/ML/LGBM_1_day.py
> +    model.save_model('trial.txt')
well these are different stories. chatgpt: ".ckpt files are designed for saving neural network states (their weights) which has no relation to boosting models. converting between these formats is neither possible nor useful"

2024-09-09 12:34 UTC, katyachemistry commented on backend/ML/LGBM_1_day.py
> +class Model:
okie

2024-09-09 13:23 UTC, Evgenii-Iurin commented on backend/ML/LGBM_1_day.py
> +    model.save_model('trial.txt')
Ok, can you provide the class method to load weights to model?

2024-09-09 13:28 UTC, katyachemistry commented on backend/ML/LGBM_1_day.py
> +    model.save_model('trial.txt')
i will add method for loading a trained model

2024-09-09 15:31 UTC, merged